# Generated by Django 5.1.4 on 2025-09-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
